### ISSUE TITLE
cannot install package without already having xarray installed

### ISSUE THREAD

**Issue by rsmith013** [cedadev/nappy#29]
the setup.py imports the version from the top level __init__.py but this also imports * from nappy_api.
This means that you cannot install unless you already have xarray. Can the version be baked into the setup.py script or the API import moved elsewhere?

**Comment by agstephens** [comment]
@rsmith013: Please try it out again. I have updated `master` and it should avoid the problem.

**Comment by rsmith013** [comment]
sorted, cheers
