### ISSUE TITLE
conversion scripts in Python 3: missing apply()

### ISSUE THREAD

**Issue by FObersteiner** [cedadev/nappy#47]
* Python version: 3.9.x
* Operating System: Ubuntu 20.04, Windows 10 (tested on both)

### Description

Scripts in the `/scripts` directory still seem to have some Python 2. That causes for example

```
[...]/nappy/nappy/script$ python na2nc.py -i '[...]/nappy/tests/testdata/1001.na' -o '[...]/test_out.nc'
Traceback (most recent call last):
  File "[...]/nappy/nappy/script/na2nc.py", line 126, in <module>
    na2nc(args)
  File "[...]/nappy/nappy/script/na2nc.py", line 120, in na2nc
    nc_file = apply(nappy.convertNAToNC, [na_file], arg_dict)
NameError: name 'apply' is not defined
```

I think this can be fixed pretty easily without breaking anything. For example in `na2nc.py`, [line 118 to 120](https://github.com/cedadev/nappy/blob/e743bad4a44d74bf5b10ab52a23cb85cf6d25970/nappy/script/na2nc.py#L118) would be replaced with 
```
nc_file = nappy.convertNAToNC(**arg_dict)
```
to run in Python 3. I can make a PR if you want.

**Comment by agstephens** [comment]
Hi @MrFuppes, thanks for spotting this. I think we need to address those scripts and create them with entry-points in the `setup.py` file. If you have the knowhow to do this then please put in PR and I'll review. Thanks
