### ISSUE TITLE
Remove CI support for Python 3.6

### ISSUE THREAD

**Issue by agstephens** [cedadev/nappy#51]
Hi @FObersteiner and @LukeJones123, you have both been active in helping improve Nappy recently. When reviewing the first Pull Request I see that it fails with Python 3.6 in the GitHub Actions CI. I don't think we need to support Python3.6 anymore. Are you happy to remove support for Python3.6?

**Comment by FObersteiner** [comment]
Hi Ag, yes I'm totally fine with dropping support for Python 3.6!

**Comment by LukeJones123** [comment]
Hi, yes, me too.

**Comment by LukeJones123** [comment]
Done.

**Comment by FObersteiner** [comment]
I think this can be closed.
