### ISSUE TITLE
Release v2.0.2

### ISSUE THREAD

**Issue by agstephens** [cedadev/nappy#59]
@FObersteiner @LukeJones123, I have released v2.0.2. Please can you try it out and let me know if there are any problems. Thanks

**Comment by FObersteiner** [comment]
Works fine for me so far. The new var & units parsing capabilities are very helpful. 

One thing that came up for me was that it might be useful (for me at least ^^) to dump VNAMEs when converting na to nc (i.e. to the `comment` global attribute. The VNAMEs I have to deal with are not exactly standard and I want to provide sufficient info on those variables in the netCDF file as well (so the user doesn't have to open the na file additionally).

**Comment by agstephens** [comment]
Hi @FObersteiner, 
I am happy for us to add extra mappings between NC and NA formats as is useful.
Do you want to propose a global attribute such as `vnames_from_source_data` ?

**Comment by FObersteiner** [comment]
> Do you want to propose a global attribute such as `vnames_from_source_data` ?

yes, that sounds reasonable.

**Comment by ReimarBauer** [comment]
Hi @agstephens 
we had to change the build recipe. Not sure what the cause is. Just connecting our changes.
https://github.com/conda-forge/nappy-feedstock/pull/9

**Comment by BastianZim** [comment]
Just to add: The `test` folder also gets installed as a separate package according to our tools which can quickly pollute a user environment. It would be good to exclude that folder and not install it.

**Comment by agstephens** [comment]
Hi @BastianZim, In the current version, we have the `tests` directory outside of the main `nappy` package. Should we be doing anything else to _exlude_ the `tests`.

**Comment by agstephens** [comment]
Thanks @BastianZim , much appreciated. I have merged your PR.

**Comment by agstephens** [comment]
The outstanding part of this issue is now caught in #61, so closing this.
