### ISSUE TITLE
Python 3 support ?

### ISSUE THREAD

**Issue by EUFAR** [cedadev/nappy#6]
Hi Ag,

Do you intend to produce a version compatible with Python 3 in the future ?
I am actually using Nappy in EGADS with Python 2.7, only for NASA Ames support, and I would like to update EGADS code to python3 if I have time before the end of EUFAR contract.

Kind regards,

Olivier

**Comment by agstephens** [comment]
Hi @eufarn7sp, 

At present we have no resource to put into upgrading nappy to Python 3. It you are able to do it I would be keen to make you a co-author of the package.

Thanks, Ag

**Comment by agstephens** [comment]
@EUFAR: an update to Python 3 should happen in tandem with #11.

**Comment by olivierpascalhenry** [comment]
Hi Ag,

That's great ! I will follow your work and probably start the migration of EGADS to Python 3 as well on my free time (I am not part of EUFAR anymore since 1 month).

**Comment by tomkralidis** [comment]
cc @ahurka

Hi all: any news on this one? We have a downstream application which we are moving to py3k. Should we start with turning on 3.5 support in a Travis PR and go from there? Does sprinkling six across the nappy code help? We might have some cycles to help this along with the appropriate direction.

**Comment by agstephens** [comment]
Hi @tomkralidis , we have just merged in some Python 3 syntax fixes into master but at the moment only the NASA Ames component works. Do you need the conversion to/from NetCDF component as well? That is where most of the hard work would be required. We would need to swap out cdat-lite for something more modern (maybe cf-python).

**Comment by tomkralidis** [comment]
Thanks @agstephens. Our [tools](https://github.com/woudc/woudc-formats) needs only the NASA Ames component.  @ahurka can you test and report back?

**Comment by ahurka** [comment]
Thanks for the Python 3 updates, looks like most of the compatibility issues were caught. A few more issues came up in our tests, fixes are suggested in #18.

**Comment by MrFuppes** [comment]
Dear nappy devs and contributors,
I'm very happy to see that something is happening towards Python3! When I just scrolled through some of the code some questions came up:
- do you plan to discontinue Python2 completely? Or will there be a "nappy2" and "nappy3"?
- I noted that the nc import/export would require a migration to netcdf4 to work with Python 3 (and also on Windows), right? (same e.g. for Numeric -> numpy)
- are there other platform-dependent features (CDAT...)?
- what did I miss?

cheers, F

**Comment by agstephens** [comment]
Hi @MrFuppes ,

Good questions. Here is a quick response to them:

 1. do you plan to discontinue Python2 completely? Or will there be a "nappy2" and "nappy3"?
   - I would favour migrating in a way that would still be Python2.7 compatible. That should not be hard.

 2. I noted that the nc import/export would require a migration to netcdf4 to work with Python 3 (and also on Windows), right? (same e.g. for Numeric -> numpy)
   - Initially we would only plan to migrate the core NASA Ames read/write functionality to Python 3. 
   - The NetCDF-conversion code would need a significant overhaul and move to either `netCDF4` or something like `cfpython`.

 3. Are there other platform-dependent features (CDAT...)?
   - The NetCDF-conversion code should work need to be migrated to tools that could run on multiple platforms. If `conda` environments were used then I think Windows-compatibility should be pretty straightforward.

 4. what did I miss?
   - I think those are all the main issues. Thanks

**Comment by agstephens** [comment]
@ReimarBauer @tomkralidis @EUFAR @MrFuppes @ahurka @olivierpascalhenry 

Tagging you all because we have updated nappy to use xarray for its netcdf conversions. The changes are on `master` but I suspect that it might still be buggy. I will cut a release soon but invite you all to test it out if you want.

Note that there are many more unit tests in the `tests` directory. Run them with:

```
pytest tests
```

**Comment by agstephens** [comment]
Python 3 now fully supported.
