### ISSUE TITLE
LICENSE file missing in pypi package

### ISSUE THREAD

**Issue by ReimarBauer** [cedadev/nappy#7]
Hi

please add the  LICENSE file to the pypi package.

I need this for a conda-forge build. Currently I have to add it manually to the recipe.

regards
Reimar

**Comment by agstephens** [comment]
Hi @ReimarBauer, I have updated the `setup.py` to pull in the license file on the GitHub master. Please can you test it works for you and then I'll push it to PyPI:

 https://github.com/cedadev/nappy

Thanks
